#include "gl_loader.h"
#include <stdio.h>

// Define function pointers
PFNGLCREATESHADERPROC glCreateShader = NULL;
PFNGLSHADERSOURCEPROC glShaderSource = NULL;
PFNGLCOMPILESHADERPROC glCompileShader = NULL;
PFNGLGETSHADERIVPROC glGetShaderiv = NULL;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = NULL;
PFNGLDELETESHADERPROC glDeleteShader = NULL;
PFNGLCREATEPROGRAMPROC glCreateProgram = NULL;
PFNGLATTACHSHADERPROC glAttachShader = NULL;
PFNGLLINKPROGRAMPROC glLinkProgram = NULL;
PFNGLGETPROGRAMIVPROC glGetProgramiv = NULL;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = NULL;
PFNGLDELETEPROGRAMPROC glDeleteProgram = NULL;
PFNGLUSEPROGRAMPROC glUseProgram = NULL;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation = NULL;
PFNGLUNIFORM1FPROC glUniform1f = NULL;
PFNGLUNIFORM4FPROC glUniform4f = NULL;
PFNGLUNIFORM2FPROC glUniform2f = NULL;
PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation = NULL;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = NULL;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = NULL;
PFNGLUNIFORM1IPROC glUniform1i = NULL;

// Helper macro for loading functions
#define LOAD_GL_FUNCTION(name, type) \
    name = (type)glXGetProcAddress((const GLubyte *)#name); \
    if (!name) { \
        fprintf(stderr, "Failed to load GL function: %s\n", #name); \
        return 0; \
    }

int load_gl_functions() {
    LOAD_GL_FUNCTION(glCreateShader, PFNGLCREATESHADERPROC);
    LOAD_GL_FUNCTION(glShaderSource, PFNGLSHADERSOURCEPROC);
    LOAD_GL_FUNCTION(glCompileShader, PFNGLCOMPILESHADERPROC);
    LOAD_GL_FUNCTION(glGetShaderiv, PFNGLGETSHADERIVPROC);
    LOAD_GL_FUNCTION(glGetShaderInfoLog, PFNGLGETSHADERINFOLOGPROC);
    LOAD_GL_FUNCTION(glDeleteShader, PFNGLDELETESHADERPROC);
    LOAD_GL_FUNCTION(glCreateProgram, PFNGLCREATEPROGRAMPROC);
    LOAD_GL_FUNCTION(glAttachShader, PFNGLATTACHSHADERPROC);
    LOAD_GL_FUNCTION(glLinkProgram, PFNGLLINKPROGRAMPROC);
    LOAD_GL_FUNCTION(glGetProgramiv, PFNGLGETPROGRAMIVPROC);
    LOAD_GL_FUNCTION(glGetProgramInfoLog, PFNGLGETPROGRAMINFOLOGPROC);
    LOAD_GL_FUNCTION(glDeleteProgram, PFNGLDELETESHADERPROC);
    LOAD_GL_FUNCTION(glUseProgram, PFNGLUSEPROGRAMPROC);
    LOAD_GL_FUNCTION(glGetUniformLocation, PFNGLGETUNIFORMLOCATIONPROC);
    LOAD_GL_FUNCTION(glUniform1f, PFNGLUNIFORM1FPROC);
    LOAD_GL_FUNCTION(glUniform4f, PFNGLUNIFORM4FPROC);
    LOAD_GL_FUNCTION(glUniform2f, PFNGLUNIFORM2FPROC);
    LOAD_GL_FUNCTION(glGetAttribLocation, PFNGLGETATTRIBLOCATIONPROC);
    LOAD_GL_FUNCTION(glVertexAttribPointer, PFNGLVERTEXATTRIBPOINTERPROC);
    LOAD_GL_FUNCTION(glEnableVertexAttribArray, PFNGLENABLEVERTEXATTRIBARRAYPROC);
    LOAD_GL_FUNCTION(glDisableVertexAttribArray, PFNGLDISABLEVERTEXATTRIBARRAYPROC);
    LOAD_GL_FUNCTION(glUniform1i, PFNGLUNIFORM1IPROC);
    return 1; // Success
}